# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mega_Mike\Desktop\B.I.G_weights-master\design\additionally.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAdditionally(object):
    def setupUi(self, DialogAdditionally):
        DialogAdditionally.setObjectName("DialogAdditionally")
        DialogAdditionally.resize(350, 225)
        DialogAdditionally.setMinimumSize(QtCore.QSize(350, 225))
        DialogAdditionally.setMaximumSize(QtCore.QSize(350, 225))
        DialogAdditionally.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.gridLayoutWidget = QtWidgets.QWidget(DialogAdditionally)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 9, 311, 204))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelPathResults = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelPathResults.setFont(font)
        self.labelPathResults.setObjectName("labelPathResults")
        self.verticalLayout_6.addWidget(self.labelPathResults)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditPathResults = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditPathResults.setObjectName("lineEditPathResults")
        self.horizontalLayout_7.addWidget(self.lineEditPathResults)
        self.pushButtonPathResults = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonPathResults.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonPathResults.setStyleSheet("image: url(:/images/images/folder.png);")
        self.pushButtonPathResults.setText("")
        self.pushButtonPathResults.setObjectName("pushButtonPathResults")
        self.horizontalLayout_7.addWidget(self.pushButtonPathResults)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelPathLog = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelPathLog.setFont(font)
        self.labelPathLog.setObjectName("labelPathLog")
        self.verticalLayout_5.addWidget(self.labelPathLog)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditPathLog = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditPathLog.setObjectName("lineEditPathLog")
        self.horizontalLayout_6.addWidget(self.lineEditPathLog)
        self.pushButtonPathLog = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonPathLog.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonPathLog.setStyleSheet("image: url(:/images/images/folder.png);")
        self.pushButtonPathLog.setText("")
        self.pushButtonPathLog.setObjectName("pushButtonPathLog")
        self.horizontalLayout_6.addWidget(self.pushButtonPathLog)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LabelBaudRate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LabelBaudRate.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)

        self.LabelBaudRate.setFont(font)
        self.LabelBaudRate.setStyleSheet("")
        self.LabelBaudRate.setObjectName("LabelBaudRate")
        self.horizontalLayout_3.addWidget(self.LabelBaudRate)


        self.comboBoxBaudRate = QtWidgets.QComboBox(self.gridLayoutWidget)

        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.horizontalLayout_3.addWidget(self.comboBoxBaudRate)
        listBaudRate = ['4800', '9600', '14400', '19200', '28800', '38400', '57600', '115200']  #список скоростей передачи данных
        self.comboBoxBaudRate.clear()
        self.comboBoxBaudRate.addItems(listBaudRate)

        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelLanguage = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLanguage.setFont(font)
        self.labelLanguage.setObjectName("labelLanguage")
        self.horizontalLayout_8.addWidget(self.labelLanguage)
        self.comboBoxLanguage = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxLanguage.setCurrentText("")
        self.comboBoxLanguage.setObjectName("fontComboBoxLanguage")
        self.horizontalLayout_8.addWidget(self.comboBoxLanguage)
        listLanguage = ['Русский', 'English']    #список языков
        self.comboBoxLanguage.clear()
        self.comboBoxLanguage.addItems(listLanguage)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)

        self.retranslateUi(DialogAdditionally)
        QtCore.QMetaObject.connectSlotsByName(DialogAdditionally)

    def retranslateUi(self, DialogAdditionally):
        _translate = QtCore.QCoreApplication.translate
        DialogAdditionally.setWindowTitle(_translate("DialogAdditionally", "Дополнительно"))
        self.labelPathResults.setText(_translate("DialogAdditionally", "Путь к файлу с результатами"))
        self.labelPathLog.setText(_translate("DialogAdditionally", "Путь к лог-файлу"))
        self.LabelBaudRate.setText(_translate("DialogAdditionally", "Скорость передачи данных"))
        self.labelLanguage.setText(_translate("DialogAdditionally", "Язык"))


import iconsadd
